### ISSUE TITLE
Missing loader information in documentation

### ISSUE THREAD

**Issue by DimmuR** [Open-E-WEB/django-powerpages#7]
Configuration section of documentation should contain information about template loader without which, you're unable to render pages.
If no loaders are specified this will work at least for django 1.10 (probably older ones aswell) - if you add:

```
'loaders': [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
    'powerpages.loader.WebsiteLoader',
]
```

to `OPTIONS` in `DjangoTemplates' (`TEMPLATES` variable setting)

**Comment by rydzopene** [comment]
Documentation updated.
Thank you
T.R.
